package config

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// WriteConfig writes a YAML config file to path, creating parent directories as needed.
func WriteConfig(path string, cfg Config) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return renderConfig(f, cfg)
}

// renderConfig writes the YAML representation of cfg to w.
func renderConfig(w io.Writer, cfg Config) error {
	fmt.Fprintf(w, "# Memory Box configuration — generated by `membox init`\n")
	fmt.Fprintf(w, "# Priority: CLI flags > MEMBOX_* env vars > this file > defaults\n\n")

	fmt.Fprintf(w, "drive:\n")
	fmt.Fprintf(w, "  mountPath: %q\n\n", cfg.Drive.MountPath)

	fmt.Fprintf(w, "parallel: %d\n\n", cfg.Parallel)

	fmt.Fprintf(w, "prune:\n")
	fmt.Fprintf(w, "  defaultDays: %d\n", cfg.Prune.DefaultDays)
	fmt.Fprintf(w, "  defaultKeep: %d\n\n", cfg.Prune.DefaultKeep)

	fmt.Fprintf(w, "sections:\n")

	order := []string{"photos", "movies", "docs", "desktop", "downloads", "icloud", "dev", "localsites", "config"}
	for _, name := range order {
		sec, ok := cfg.Sections[name]
		if !ok {
			continue
		}
		writeSectionEntry(w, name, sec)
	}
	return nil
}

func writeSectionEntry(w io.Writer, name string, sec SectionConfig) {
	fmt.Fprintf(w, "  %s:\n", name)
	fmt.Fprintf(w, "    enabled: %v\n", sec.Enabled)
	if len(sec.Excludes) > 0 {
		fmt.Fprintf(w, "    excludes:\n")
		for _, ex := range sec.Excludes {
			if strings.ContainsAny(ex, " *?[]{}") {
				fmt.Fprintf(w, "      - %q\n", ex)
			} else {
				fmt.Fprintf(w, "      - %s\n", ex)
			}
		}
	}
}
